name: Déploiement sur Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    needs: test  # Nécessite que le job "test" passe
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Assure l'historique complet pour le push Git

      - name: Installer Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Vérifier Heroku CLI
        run: heroku --version

      - name: Ajouter la télécommande Git Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku git:remote -a ton-app-heroku
          git remote set-url heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/ton-app-heroku.git

      - name: Vérifier les télécommandes Git
        run: git remote -v

      - name: Déployer sur Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: git push heroku master --force
