name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          extensions: sqlite

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-scripts

      - name: Run migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction --env=test
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/var/test.db
          APP_ENV: test

      - name: Run PHPUnit
        run: php bin/phpunit --env=test
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/var/test.db
          APP_ENV: test
