name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          extensions: mbstring, intl, pdo_sqlite

      - name: Setup Composer Cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.2-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php8.2-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Install importmap assets
        env:
          APP_ENV: test
          DATABASE_URL: sqlite:///%kernel.project_dir%/var/test.db
        run: php bin/console importmap:install

      - name: Run Doctrine Migrations
        env:
          APP_ENV: test
          DATABASE_URL: sqlite:///%kernel.project_dir%/var/test.db
        run: php bin/console doctrine:migrations:migrate --no-interaction

      - name: Run PHPUnit
        env:
          APP_ENV: test
          DATABASE_URL: sqlite:///%kernel.project_dir%/var/test.db
        run: php bin/phpunit --testsuite=default
