name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Tests Symfony
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: sqlite, pdo_sqlite
          tools: composer:v2

      - name: Setup Composer Cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.2-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php8.2-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-scripts --no-progress

      - name: Clear cache for test environment
        run: php bin/console cache:clear --env=test

      - name: Create test database
        run: php bin/console doctrine:database:create --env=test || true

      - name: Run migrations for test database
        run: php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Install importmap assets
        run: php bin/console importmap:install

      - name: Run PHPUnit
        run: php bin/phpunit
        env:
          APP_ENV: test
          DATABASE_URL: "sqlite:///%kernel.project_dir%/var/test.db"
          APP_SECRET: testsecret
