name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Symfony Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          extensions: pdo_sqlite, intl

      - name: Set environment variables for test
        run: |
          echo "APP_ENV=test" >> $GITHUB_ENV
          echo "KERNEL_CLASS=App\Kernel" >> $GITHUB_ENV
          echo "APP_SECRET=\$ecretf0rt3st" >> $GITHUB_ENV
          echo "DATABASE_URL=sqlite:///%kernel.project_dir%/var/test.db" >> $GITHUB_ENV

      - name: Setup Composer Cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.2-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php8.2-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Clear cache for test env
        run: php bin/console cache:clear --env=test

      - name: Run PHPUnit
        run: php bin/phpunit
        env:
          APP_ENV: test
