name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    services:
      database:
        image: mariadb:10.7.3
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
          MARIADB_DATABASE: symfony_test
        ports:
          - 3306/tcp
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          extensions: pdo_mysql, intl, mbstring, xdebug

      - name: Setup Composer Cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.2-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php8.2-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-scripts --no-progress

      - name: Install importmap assets
        run: php bin/console importmap:install

      - name: Wait for DB
        run: sleep 10

      - name: Run migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction
        env:
          APP_ENV: test
          DATABASE_URL: mysql://root:@127.0.0.1:${{ job.services.database.ports['3306'] }}/symfony_test

      - name: Run PHPUnit
        run: php bin/phpunit --testdox
        env:
          APP_ENV: test
          DATABASE_URL: mysql://root:@127.0.0.1:${{ job.services.database.ports['3306'] }}/symfony_test
