name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    services:
      database:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: symfony_test
          MYSQL_USER: symfony
          MYSQL_PASSWORD: symfony
        ports:
          - 3306/tcp
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          extensions: mbstring, intl, pdo_mysql

      - name: Setup Composer Cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.2-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php8.2-composer-

      - name: Install Composer dependencies (without scripts)
        run: composer install --prefer-dist --no-interaction --no-progress --no-scripts

      - name: Run Symfony auto-scripts
        env:
          APP_ENV: test
          DATABASE_URL: mysql://symfony:symfony@127.0.0.1:3306/symfony_test
        run: composer run-script symfony-auto-scripts

      - name: Install importmap assets
        env:
          APP_ENV: test
          DATABASE_URL: mysql://symfony:symfony@127.0.0.1:3306/symfony_test
        run: php bin/console importmap:install

      - name: Wait for DB
        run: sleep 10

      - name: Run PHPUnit
        env:
          APP_ENV: test
          DATABASE_URL: mysql://symfony:symfony@127.0.0.1:3306/symfony_test
        run: php bin/phpunit --testsuite=default
